version: '3.5'
services:
  restapi:
    image: ghcr.io/eloyasr/tfg/restapi:latest
    ports:
      - "5000:5000"
  webapp:
    image: ghcr.io/eloyasr/tfg/webapp:latest
    ports:
      - "3000:3000"
    depends_on: 
      - restapi
